///////////////////////////////////////////////////////////////////
// generated by ./generate_status_codes.sh, do not edit manually!
///////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>

#pragma once

extern const NSInteger BC_HTTP_ACCEPTED;
extern const NSInteger BC_HTTP_BAD_GATEWAY;
extern const NSInteger BC_HTTP_BAD_METHOD;
extern const NSInteger BC_HTTP_BAD_REQUEST;
extern const NSInteger BC_HTTP_CLIENT_TIMEOUT;
extern const NSInteger BC_HTTP_CONFLICT;
extern const NSInteger BC_HTTP_CREATED;
extern const NSInteger BC_HTTP_ENTITY_TOO_LARGE;
extern const NSInteger BC_HTTP_FORBIDDEN;
extern const NSInteger BC_HTTP_GATEWAY_TIMEOUT;
extern const NSInteger BC_HTTP_GONE;
extern const NSInteger BC_HTTP_INTERNAL_ERROR;
extern const NSInteger BC_HTTP_LENGTH_REQUIRED;
extern const NSInteger BC_HTTP_MOVED_PERM;
extern const NSInteger BC_HTTP_MOVED_TEMP;
extern const NSInteger BC_HTTP_MULT_CHOICE;
extern const NSInteger BC_HTTP_NO_CONTENT;
extern const NSInteger BC_HTTP_NOT_ACCEPTABLE;
extern const NSInteger BC_HTTP_NOT_AUTHORITATIVE;
extern const NSInteger BC_HTTP_NOT_FOUND;
extern const NSInteger BC_HTTP_NOT_IMPLEMENTED;
extern const NSInteger BC_HTTP_NOT_MODIFIED;
extern const NSInteger BC_HTTP_OK;
extern const NSInteger BC_HTTP_PARTIAL;
extern const NSInteger BC_HTTP_PAYMENT_REQUIRED;
extern const NSInteger BC_HTTP_PRECON_FAILED;
extern const NSInteger BC_HTTP_PROXY_AUTH;
extern const NSInteger BC_HTTP_REQ_TOO_LONG;
extern const NSInteger BC_HTTP_RESET;
extern const NSInteger BC_HTTP_SEE_OTHER;
extern const NSInteger BC_HTTP_SERVER_ERROR;
extern const NSInteger BC_HTTP_UNAUTHORIZED;
extern const NSInteger BC_HTTP_UNAVAILABLE;
extern const NSInteger BC_HTTP_UNSUPPORTED_TYPE;
extern const NSInteger BC_HTTP_USE_PROXY;
extern const NSInteger BC_HTTP_VERSION;
extern const NSInteger BC_HTTP_CUSTOM;
extern const NSInteger BC_HTTP_CLIENT_NETWORK_ERROR;

